# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller build specification for kobs-plotter.

Driven by ``.github/workflows/release.yml`` via ``pyinstaller --clean
kobs-plotter.spec`` on both Windows and Linux. Platform differences (icon,
console, Windows version resource) are resolved here from ``sys.platform``
so the workflow is a single command per OS.

Startup-latency notes:
  - ``excludes`` trims transitive test/dev machinery and the matplotlib
    backends kobs-plotter never uses (only QtAgg + Agg are imported).
  - ``optimize=2`` strips docstrings/asserts from the PYZ archive.
  - ``Splash`` shows the bootloader splash during interpreter + library
    init (the slow part) and hands off to the in-app Qt splash via
    ``pyi_splash.close()`` in ``main.py``.
  - ``upx=False``: compression skipped per project decision (avoid Windows
    antivirus false positives and binary-stripping breakage).
"""

import os
import sys

_IS_WINDOWS = sys.platform == "win32"

# Windows VS_VERSION_INFO resource (Properties -> Details tab: company,
# product, version, copyright). Generated by the release workflow from
# pyproject.toml. Only attached on Windows; absent -> no version resource.
_version_file = (
    "version_info.txt"
    if _IS_WINDOWS and os.path.exists("version_info.txt")
    else None
)

_icon = (
    "src/kobs_plotter/assets/icons/logo.ico"
    if _IS_WINDOWS
    else "src/kobs_plotter/assets/icons/logo.png"
)

# Modules pulled in transitively by the scientific stack that kobs-plotter
# never uses. Excluding shrinks the bundle and trims cold-start import work.
# NOTE: stdlib test/build modules (unittest, doctest, pydoc, setuptools, pip,
# distutils) and matplotlib's file-output backends (pdf/svg/ps/cairo) are
# intentionally NOT excluded — pyparsing imports unittest at module load
# (pulled in by matplotlib), and the file backends back the plot window's
# Save-Figure export to those formats.
_excludes = [
    # Alternative GUI toolkits / bindings not used (PySide6 only).
    "tkinter",
    "PyQt4",
    "PyQt5",
    "PyQt6",
    "PySide2",
    # Unused matplotlib *interactive* backends — kobs-plotter uses QtAgg + Agg.
    "matplotlib.backends.backend_tkagg",
    "matplotlib.backends.backend_gtk3agg",
    "matplotlib.backends.backend_gtk4agg",
    "matplotlib.backends.backend_wxagg",
    "matplotlib.backends.backend_wx",
    "matplotlib.backends.backend_qt5agg",
    "matplotlib.backends.backend_macosx",
    # Dev / notebook infrastructure pulled in transitively (not used at runtime).
    "pytest",
    "IPython",
    "jupyter",
    "jupyter_client",
    "jupyter_core",
    "notebook",
    "jedi",
    # Test subpackages of the scientific stack — never imported at runtime.
    "numpy.tests",
    "pandas.tests",
    "scipy.tests",
    "scipy.linalg.tests",
]


a = Analysis(
    ["src/kobs_plotter/main.py"],
    pathex=[],
    binaries=[],
    datas=[("src/kobs_plotter/assets", "kobs_plotter/assets")],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=_excludes,
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)
splash = Splash(
    "src/kobs_plotter/assets/icons/splash.png",
    binaries=a.binaries,
    datas=a.datas,
    text_pos=(20, 670),
    text_size=12,
    text_color="white",
    minify_script=True,
    always_on_top=True,
)

exe = EXE(
    pyz,
    a.scripts,
    splash,
    [],
    exclude_binaries=True,
    name="kobs-plotter",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=not _IS_WINDOWS,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=[_icon],
    version=_version_file,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    splash.binaries,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="kobs-plotter",
)
